name: aind
channels:
- defaults
dependencies:
- bleach=1.5.0=py36_0
- colorama=0.3.7=py36_0
- cycler=0.10.0=py36_0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- html5lib=0.999=py36_0
- icu=57.1=vc14_0
- ipykernel=4.5.2=py36_0
- ipython=5.3.0=py36_0
- ipython_genutils=0.1.0=py36_0
- ipywidgets=6.0.0=py36_0
- jinja2=2.9.5=py36_0
- jpeg=9b=vc14_0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=5.0.0=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libpng=1.6.27=vc14_0
- markupsafe=0.23=py36_2
- matplotlib=2.0.0=np111py36_0
- mistune=0.7.4=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.3.0=py36_0
- notebook=4.4.1=py36_0
- numpy=1.11.3=py36_0
- openssl=1.0.2k=vc14_0
- pandas=0.19.2=np111py36_1
- pandocfilters=1.4.1=py36_0
- path.py=10.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.13=py36_0
- py=1.4.32=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.1.4=py36_0
- pyqt=5.6.0=py36_2
- pytest=3.0.7=py36_0
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=vc14_3
- qtconsole=4.2.1=py36_2
- scikit-learn=0.18.1=np111py36_1
- scipy=0.18.1=np111py36_1
- setuptools=27.2.0=py36_1
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=vc14_0
- tornado=4.4.2=py36_0
- traitlets=4.3.2=py36_0
- vs2015_runtime=14.0.25123=0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- zlib=1.2.8=vc14_3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==5.0.0
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.13
  - udacity-pa>=0.2
